name: CI 
on: 
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest 
    steps: 
      - uses: action/checkout@v2 
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "16"
      - run: npm ci  # like npm install, but more suitable for ci
      - run: npm run format:check
      - run: npm test -- --coverage 
        env:
          CI: true
      

